---
abstract: 'Excel export for DBIx::Class using Spreedsheet::WriteExcel'
author:
  - 'Sean Zellmer <sean@lejeunerenard.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.027
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-ResultSet-Excel
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  DBIx::Class: 0.08250
  File::Temp: 0
  Spreadsheet::WriteExcel: 2.39
  perl: 5.008005
resources:
  bugtracker: https://github.com/lejeunerenard/DBIx-Class-ResultSet-Excel/issues
  homepage: https://github.com/lejeunerenard/DBIx-Class-ResultSet-Excel
  repository: https://github.com/lejeunerenard/DBIx-Class-ResultSet-Excel.git
version: 0.01
